# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/data/Code/Python/GenAlg/forms/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(290, 99999))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.choosesizeEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.choosesizeEdit.setInputMask("")
        self.choosesizeEdit.setObjectName("choosesizeEdit")
        self.gridLayout_4.addWidget(self.choosesizeEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.mutsizeEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.mutsizeEdit.setInputMask("")
        self.mutsizeEdit.setObjectName("mutsizeEdit")
        self.gridLayout_4.addWidget(self.mutsizeEdit, 2, 1, 1, 1)
        self.popsizeEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.popsizeEdit.setInputMask("")
        self.popsizeEdit.setObjectName("popsizeEdit")
        self.gridLayout_4.addWidget(self.popsizeEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.breakEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.breakEdit.setInputMask("")
        self.breakEdit.setObjectName("breakEdit")
        self.gridLayout_4.addWidget(self.breakEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.findSolutionButton = QtWidgets.QPushButton(self.groupBox_4)
        self.findSolutionButton.setObjectName("findSolutionButton")
        self.gridLayout_4.addWidget(self.findSolutionButton, 4, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delGoodButton = QtWidgets.QPushButton(self.groupBox)
        self.delGoodButton.setObjectName("delGoodButton")
        self.gridLayout_2.addWidget(self.delGoodButton, 1, 2, 1, 1)
        self.addGoodButton = QtWidgets.QPushButton(self.groupBox)
        self.addGoodButton.setObjectName("addGoodButton")
        self.gridLayout_2.addWidget(self.addGoodButton, 1, 0, 1, 1)
        self.goodsView = QtWidgets.QTableView(self.groupBox)
        self.goodsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.goodsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.goodsView.setObjectName("goodsView")
        self.goodsView.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.goodsView, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.addResButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addResButton.setObjectName("addResButton")
        self.gridLayout.addWidget(self.addResButton, 1, 0, 1, 1)
        self.delResButton = QtWidgets.QPushButton(self.groupBox_2)
        self.delResButton.setObjectName("delResButton")
        self.gridLayout.addWidget(self.delResButton, 1, 1, 1, 1)
        self.resView = QtWidgets.QTableView(self.groupBox_2)
        self.resView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.resView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.resView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.resView.setObjectName("resView")
        self.resView.horizontalHeader().setStretchLastSection(True)
        self.resView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.resView, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 3)
        self.resResultTable = QtWidgets.QTabWidget(self.centralwidget)
        self.resResultTable.setObjectName("resResultTable")
        self.goodsTab = QtWidgets.QWidget()
        self.goodsTab.setObjectName("goodsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.goodsTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.goodResultTable = QtWidgets.QTableWidget(self.goodsTab)
        self.goodResultTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.goodResultTable.setObjectName("goodResultTable")
        self.goodResultTable.setColumnCount(3)
        self.goodResultTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.goodResultTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.goodResultTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.goodResultTable.setHorizontalHeaderItem(2, item)
        self.goodResultTable.horizontalHeader().setStretchLastSection(True)
        self.goodResultTable.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.goodResultTable, 0, 0, 1, 1)
        self.resResultTable.addTab(self.goodsTab, "")
        self.resTab = QtWidgets.QWidget()
        self.resTab.setObjectName("resTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.resTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.resResultTable_2 = QtWidgets.QTableWidget(self.resTab)
        self.resResultTable_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resResultTable_2.setObjectName("resResultTable_2")
        self.resResultTable_2.setColumnCount(3)
        self.resResultTable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resResultTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resResultTable_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resResultTable_2.setHorizontalHeaderItem(2, item)
        self.resResultTable_2.horizontalHeader().setStretchLastSection(True)
        self.resResultTable_2.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.resResultTable_2, 0, 0, 1, 1)
        self.resResultTable.addTab(self.resTab, "")
        self.gridLayout_5.addWidget(self.resResultTable, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file_open = QtWidgets.QAction(MainWindow)
        self.file_open.setObjectName("file_open")
        self.file_save = QtWidgets.QAction(MainWindow)
        self.file_save.setObjectName("file_save")
        self.file_exit = QtWidgets.QAction(MainWindow)
        self.file_exit.setObjectName("file_exit")
        self.menu.addAction(self.file_open)
        self.menu.addAction(self.file_save)
        self.menu.addSeparator()
        self.menu.addAction(self.file_exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.resResultTable.setCurrentIndex(0)
        self.file_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.goodsView, self.resView)
        MainWindow.setTabOrder(self.resView, self.addGoodButton)
        MainWindow.setTabOrder(self.addGoodButton, self.delGoodButton)
        MainWindow.setTabOrder(self.delGoodButton, self.addResButton)
        MainWindow.setTabOrder(self.addResButton, self.delResButton)
        MainWindow.setTabOrder(self.delResButton, self.popsizeEdit)
        MainWindow.setTabOrder(self.popsizeEdit, self.choosesizeEdit)
        MainWindow.setTabOrder(self.choosesizeEdit, self.mutsizeEdit)
        MainWindow.setTabOrder(self.mutsizeEdit, self.breakEdit)
        MainWindow.setTabOrder(self.breakEdit, self.findSolutionButton)
        MainWindow.setTabOrder(self.findSolutionButton, self.resResultTable)
        MainWindow.setTabOrder(self.resResultTable, self.goodResultTable)
        MainWindow.setTabOrder(self.goodResultTable, self.resResultTable_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генетический Алгоритм"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Параметры алгоритма"))
        self.label_4.setText(_translate("MainWindow", "Число холостых итераций:"))
        self.choosesizeEdit.setText(_translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "Число отбираемых решений:"))
        self.mutsizeEdit.setText(_translate("MainWindow", "20"))
        self.popsizeEdit.setText(_translate("MainWindow", "100"))
        self.label.setText(_translate("MainWindow", "Численность популяции:"))
        self.breakEdit.setText(_translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", "Число мутаций:"))
        self.findSolutionButton.setText(_translate("MainWindow", "Найти решение"))
        self.groupBox.setTitle(_translate("MainWindow", "Список и стоимость товаров"))
        self.delGoodButton.setText(_translate("MainWindow", "Удалить"))
        self.addGoodButton.setText(_translate("MainWindow", "Добавить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Доступные ресурсы"))
        self.addResButton.setText(_translate("MainWindow", "Добавить"))
        self.delResButton.setText(_translate("MainWindow", "Удалить"))
        item = self.goodResultTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Товар"))
        item = self.goodResultTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Кол-во"))
        item = self.goodResultTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Стоимость"))
        self.resResultTable.setTabText(self.resResultTable.indexOf(self.goodsTab), _translate("MainWindow", "Товары"))
        item = self.resResultTable_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ресурс"))
        item = self.resResultTable_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Затраты"))
        item = self.resResultTable_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Остаток"))
        self.resResultTable.setTabText(self.resResultTable.indexOf(self.resTab), _translate("MainWindow", "Ресурсы"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.file_open.setText(_translate("MainWindow", "Открыть"))
        self.file_open.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.file_save.setText(_translate("MainWindow", "Сохранить как"))
        self.file_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.file_exit.setText(_translate("MainWindow", "Выход"))
        self.file_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

