# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/data/Code/Python/GenAlg/forms/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 439)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delGoodButton = QtWidgets.QPushButton(self.groupBox)
        self.delGoodButton.setObjectName("delGoodButton")
        self.gridLayout_2.addWidget(self.delGoodButton, 1, 2, 1, 1)
        self.addGoodButton = QtWidgets.QPushButton(self.groupBox)
        self.addGoodButton.setObjectName("addGoodButton")
        self.gridLayout_2.addWidget(self.addGoodButton, 1, 0, 1, 1)
        self.goodsView = QtWidgets.QTableView(self.groupBox)
        self.goodsView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.goodsView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.goodsView.setObjectName("goodsView")
        self.goodsView.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.goodsView, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.addResButton = QtWidgets.QPushButton(self.groupBox_2)
        self.addResButton.setObjectName("addResButton")
        self.gridLayout.addWidget(self.addResButton, 1, 0, 1, 1)
        self.delResButton = QtWidgets.QPushButton(self.groupBox_2)
        self.delResButton.setObjectName("delResButton")
        self.gridLayout.addWidget(self.delResButton, 1, 1, 1, 1)
        self.resView = QtWidgets.QTableView(self.groupBox_2)
        self.resView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.resView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.resView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.resView.setObjectName("resView")
        self.resView.horizontalHeader().setStretchLastSection(True)
        self.resView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.resView, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.splitter)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.findSolutionButton = QtWidgets.QPushButton(self.groupBox_3)
        self.findSolutionButton.setObjectName("findSolutionButton")
        self.horizontalLayout.addWidget(self.findSolutionButton)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file_open = QtWidgets.QAction(MainWindow)
        self.file_open.setObjectName("file_open")
        self.file_save = QtWidgets.QAction(MainWindow)
        self.file_save.setObjectName("file_save")
        self.file_exit = QtWidgets.QAction(MainWindow)
        self.file_exit.setObjectName("file_exit")
        self.menu.addAction(self.file_open)
        self.menu.addAction(self.file_save)
        self.menu.addSeparator()
        self.menu.addAction(self.file_exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.file_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.goodsView, self.resView)
        MainWindow.setTabOrder(self.resView, self.addGoodButton)
        MainWindow.setTabOrder(self.addGoodButton, self.delGoodButton)
        MainWindow.setTabOrder(self.delGoodButton, self.addResButton)
        MainWindow.setTabOrder(self.addResButton, self.delResButton)
        MainWindow.setTabOrder(self.delResButton, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.findSolutionButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Генетический Алгоритм"))
        self.groupBox.setTitle(_translate("MainWindow", "Список и стоимость товаров"))
        self.delGoodButton.setText(_translate("MainWindow", "Удалить"))
        self.addGoodButton.setText(_translate("MainWindow", "Добавить"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Доступные ресурсы"))
        self.addResButton.setText(_translate("MainWindow", "Добавить"))
        self.delResButton.setText(_translate("MainWindow", "Удалить"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Решение"))
        self.findSolutionButton.setText(_translate("MainWindow", "Найти"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.file_open.setText(_translate("MainWindow", "Открыть"))
        self.file_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.file_save.setText(_translate("MainWindow", "Сохранить как"))
        self.file_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.file_exit.setText(_translate("MainWindow", "Выход"))
        self.file_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

